# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

FROM quay.io/almalinuxorg/almalinux-bootc:10.2-20261008 AS common
RUN --mount=type=bind,source=target/common/rpm,target=/tmp/RPMS,ro,z \
    --mount=type=tmpfs,target=/run \
    --mount=type=tmpfs,target=/var/cache \
    --mount=type=tmpfs,target=/var/lib \
    --mount=type=tmpfs,target=/var/log <<'EOF'
dnf install -y \
  https://download1.rpmfusion.org/free/el/rpmfusion-free-release-10.noarch.rpm \
  https://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-10.noarch.rpm \
  /tmp/RPMS/*.rpm
EOF
RUN bootc container lint --fatal-warnings

FROM common AS installer
RUN --mount=type=bind,source=target/installer/rpm,target=/tmp/RPMS,ro,z \
    --mount=type=tmpfs,target=/run \
    --mount=type=tmpfs,target=/var/cache \
    --mount=type=tmpfs,target=/var/lib \
    --mount=type=tmpfs,target=/var/log <<'EOF'
dnf install -y /tmp/RPMS/*.rpm
dnf reinstall -y shim-x64
EOF
RUN bootc container lint --fatal-warnings --skip nonempty-boot

FROM common AS payload
RUN --mount=type=bind,source=target/payload/rpm,target=/tmp/RPMS,ro,z \
    --mount=type=tmpfs,target=/run \
    --mount=type=tmpfs,target=/var/cache \
    --mount=type=tmpfs,target=/var/lib \
    --mount=type=tmpfs,target=/var/log <<'EOF'
dnf install -y \
  @multimedia \
  @sound-and-video \
  @workstation-product-environment \
  /tmp/RPMS/*.rpm
EOF
RUN bootc container lint --fatal-warnings
