# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

---
version: "3"

includes:
  common: "{{.G_HELPER}}"
  installer: "{{.G_HELPER}}"
  iso: src/iso
  payload: "{{.G_HELPER}}"

dotenv: [".env"]

run: when_changed

env: {RELEASE: 1, VERSION: 0.3.0}

vars:
  G_COMPONENTS: [common, installer, payload]
  G_HELPER: src/helper
  G_NAME: workstation
  G_REGISTRY: ghcr.io/theomund/{{.G_NAME}}
  G_SUFFIX: "{{.VERSION}}-{{.RELEASE}}"

  G_CONTAINER_FORMAT: >-
    target/%[1]s/container/{{.G_NAME}}-%[1]s-{{.G_SUFFIX}}-iid.txt
  G_ISO_FORMAT: target/iso/%[1]s/{{.G_NAME}}-{{.G_SUFFIX}}-%[1]s.iso
  G_OCI_FORMAT: target/%[1]s/oci/{{.G_NAME}}-%[1]s-{{.G_SUFFIX}}-oci.tar
  G_TAG_FORMAT: "{{.G_REGISTRY}}/%s:{{.G_SUFFIX}}"

tasks:
  ci:
    desc: Run CI/CD pipeline.
    cmds: [{task: lint}, {task: iso}]

  clean:
    desc: Clean the project.
    cmd: git clean -fdxe '.env'

  container:
    desc: Build all container images.
    deps: &components
      - for: {var: G_COMPONENTS}
        task: "{{.ITEM}}:{{.TASK}}"

  cve: {desc: "Build all CVE tables.", deps: *components}

  db:
    desc: Update CVE database.
    cmd: grype db update

  default:
    desc: Print project tasks.
    silent: true
    cmd: task -l

  iso:
    desc: Build all ISO images.
    deps: [iso:install, iso:upgrade]

  lint:
    desc: Lint the source code.
    deps: [lint:rpmlint, lint:shellcheck, lint:yamllint]

  lint:rpmlint:
    desc: Lint the RPM packages.
    deps: [rpm]
    cmd: rpmlint "target/"*"/rpm/"*".src.rpm"

  lint:shellcheck:
    desc: Lint the shell scripts.
    cmd: shellcheck
         "src/iso/upgrade/upgrade.sh"
         "src/payload/rootfs/usr/libexec/{{.G_NAME}}-payload"

  lint:yamllint:
    desc: Lint the YAML files.
    cmd: yamllint "."

  rootfs: {desc: "Build all root filesystem archives.", deps: *components}

  rpm: {desc: "Build all RPM packages.", deps: *components}

  sbom: {desc: "Build all SBOM files.", deps: *components}
