# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

ARG BASE

FROM ${BASE} AS installer
RUN --mount=type=bind,source=target/installer/rpm,target=/tmp/RPMS,ro,z \
    --mount=type=tmpfs,target=/run \
    --mount=type=tmpfs,target=/var/cache \
    --mount=type=tmpfs,target=/var/lib \
    --mount=type=tmpfs,target=/var/log <<'EOF'
dnf install -y /tmp/RPMS/*.rpm
dnf reinstall -y shim-x64
EOF
RUN bootc container lint --fatal-warnings --skip nonempty-boot
