# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

---
version: "3"

vars:
  PREFIX: workstation-{{.COMPONENT}}-{{.SUFFIX}}
  SOURCE: src/{{.COMPONENT}}
  TARGET: target/{{.COMPONENT}}
  CONTAINER: "{{.TARGET}}/container/{{.PREFIX}}-container.tar"
  CVE: "{{.TARGET}}/cve/{{.PREFIX}}-cve.txt"
  ROOTFS: "{{.TARGET}}/rootfs/{{.PREFIX}}-rootfs.tar.gz"
  RPM: "{{.TARGET}}/rpm/{{.PREFIX}}.el10.x86_64.rpm"
  SBOM: "{{.TARGET}}/sbom/{{.PREFIX}}-sbom.json"
  SRPM: "{{.TARGET}}/srpm/{{.PREFIX}}.el10.src.rpm"

tasks:
  container:
    desc: Build {{.COMPONENT}} container.
    vars:
      BASE: "{{.REGISTRY}}/common:{{.SUFFIX}}"
      CONTAINERFILE: "{{.SOURCE}}/container/Containerfile"
      ROOT: "{{.TARGET}}/container/root"
      TAG: "{{.REGISTRY}}/{{.COMPONENT}}:{{.SUFFIX}}"
      TAR: target/common/container/workstation-common-{{.SUFFIX}}-container.tar
    sources:
      - "{{.CONTAINERFILE}}"
      - "{{.RPM}}"
      - '{{if ne .COMPONENT "common"}}{{.TAR}}{{end}}'
    generates:
      - "{{.CONTAINER}}"
    deps:
      - container:base
      - rpm
    cmds:
      - mkdir -p {{.ROOT}}
      - defer: rm -rf {{.ROOT}}
      - podman-remote build
        {{if ne .COMPONENT "common"}}
        --build-arg BASE={{.BASE}}
        {{end}}
        {{if eq .COMPONENT "payload"}}
        --build-arg CHUNKAH_CHOWN="$(id -u):$(id -g)"
        --build-arg CHUNKAH_CONFIG_STR="$(podman-remote inspect {{.BASE}})"
        --build-arg CHUNKAH_OUTPUT=$WORKSPACE_PATH/{{.ROOT}}/out
        --security-opt label=disable
        --skip-unused-stages=false
        -v $WORKSPACE_PATH/{{.ROOT}}:/run/src
        {{end}}
        -f {{.CONTAINERFILE}}
        -t {{.TAG}}
        .
      - podman-remote save --format oci-archive -o {{.CONTAINER}} {{.TAG}}

  container:base:
    internal: true
    if: '{{ne .COMPONENT "common"}}'
    deps:
      - :common:container

  cve:
    desc: Build {{.COMPONENT}} CVE table.
    env:
      NO_COLOR: "1"
    sources:
      - "{{.SBOM}}"
    generates:
      - "{{.CVE}}"
    deps:
      - :db
      - sbom
    cmds:
      - grype sbom:{{.SBOM}} -o table={{.CVE}}

  rootfs:
    desc: Build {{.COMPONENT}} root filesystem archive.
    vars:
      FILES: "{{.SOURCE}}/rootfs"
    sources:
      - "{{.FILES}}/**/*"
    generates:
      - "{{.ROOTFS}}"
    cmds:
      - mkdir -p {{.TARGET}}/rootfs
      - tar --exclude '.gitkeep' -czvf {{.ROOTFS}} -C {{.FILES}} .

  rpm:
    desc: Build {{.COMPONENT}} RPM package.
    env:
      TOP_DIR: "{{.ROOT_DIR}}/{{.TARGET}}/rpm/root"
    sources:
      - "{{.SRPM}}"
    generates:
      - "{{.RPM}}"
    deps:
      - srpm
    cmds:
      - defer: rm -rf $TOP_DIR
      - rpmbuild --rebuild {{.SRPM}}
      - mv $TOP_DIR/RPMS/x86_64/*.rpm {{.TARGET}}/rpm

  srpm:
    desc: Build {{.COMPONENT}} SRPM package.
    env:
      ROOTFS_DIR: "{{.ROOT_DIR}}/{{.TARGET}}/rootfs"
      SRPM_DIR: "{{.ROOT_DIR}}/{{.TARGET}}/srpm"
      TOP_DIR: "{{.ROOT_DIR}}/{{.TARGET}}/srpm/root"
    vars:
      SPEC: "{{.SOURCE}}/srpm/workstation-{{.COMPONENT}}.spec"
    sources:
      - "{{.ROOTFS}}"
      - "{{.SPEC}}"
    generates:
      - "{{.SRPM}}"
    deps:
      - rootfs
    cmds:
      - defer: rm -rf $TOP_DIR
      - rpmbuild -bs {{.SPEC}}

  sbom:
    desc: Build {{.COMPONENT}} SBOM file.
    env:
      SYFT_GOLANG_CAPTURE_SYMBOLS: all
    sources:
      - "{{.CONTAINER}}"
    generates:
      - "{{.SBOM}}"
    deps:
      - container
    cmds:
      - syft oci-archive:{{.CONTAINER}} -o syft-json={{.SBOM}}
