# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

---
version: "3"

vars:
  G_PREFIX: "{{.G_NAME}}-{{.G_COMPONENT}}-{{.G_SUFFIX}}"
  G_SOURCE: src/{{.G_COMPONENT}}
  G_TAG: "{{.G_REGISTRY}}/{{.G_COMPONENT}}:{{.G_SUFFIX}}"

  G_TARGET: target/{{.G_COMPONENT}}
  G_CONTAINER: "{{.G_TARGET}}/container/{{.G_PREFIX}}-iid.txt"
  G_CVE: "{{.G_TARGET}}/cve/{{.G_PREFIX}}-cve.txt"
  G_OCI: "{{.G_TARGET}}/container/{{.G_PREFIX}}-oci.tar"
  G_ROOTFS: "{{.G_TARGET}}/rootfs/{{.G_PREFIX}}-rootfs.tar.gz"
  G_RPM: "{{.G_TARGET}}/rpm/{{.G_PREFIX}}.el10.x86_64.rpm"
  G_SBOM: "{{.G_TARGET}}/sbom/{{.G_PREFIX}}-sbom.json"
  G_SRPM: "{{.G_TARGET}}/rpm/{{.G_PREFIX}}.el10.src.rpm"

tasks:
  container:
    desc: Build {{.G_COMPONENT}} container.
    vars:
      BASE_ID: target/common/container/{{.G_NAME}}-common-{{.G_SUFFIX}}-iid.txt
      BASE_TAG: "{{.G_REGISTRY}}/common:{{.G_SUFFIX}}"
      CONTAINERFILE: "{{.G_SOURCE}}/container/Containerfile"
      ROOT: "{{.G_TARGET}}/container/root"
    sources:
      - "{{.CONTAINERFILE}}"
      - "{{.G_RPM}}"
      - '{{if ne .G_COMPONENT "common"}}{{.BASE_ID}}{{end}}'
    generates:
      - "{{.G_CONTAINER}}"
    deps:
      - container:base
      - rpm
    status:
      - podman-remote image exists {{.G_TAG}}
    cmds:
      - mkdir -p "{{.ROOT}}"
      - defer: rm -rf "{{.ROOT}}"
      - podman-remote build
        --iidfile "{{.G_CONTAINER}}"
        {{if ne .G_COMPONENT "common"}}
        --build-arg BASE={{.BASE_TAG}}
        {{end}}
        {{if eq .G_COMPONENT "payload"}}
        --build-arg CHUNKAH_CHOWN="$(id -u):$(id -g)"
        --build-arg CHUNKAH_CONFIG_STR="$(podman-remote inspect {{.BASE_TAG}})"
        --build-arg CHUNKAH_OUTPUT="$WORKSPACE_PATH/{{.ROOT}}/out"
        --security-opt label=disable
        --skip-unused-stages=false
        -v "$WORKSPACE_PATH/{{.ROOT}}:/run/src"
        {{end}}
        -f "{{.CONTAINERFILE}}"
        -t {{.G_TAG}}
        "."

  cve:
    desc: Build {{.G_COMPONENT}} CVE table.
    env:
      NO_COLOR: "1"
    sources:
      - "{{.G_SBOM}}"
    generates:
      - "{{.G_CVE}}"
    deps:
      - :db
      - sbom
    cmds:
      - grype sbom:"{{.G_SBOM}}" -o table="{{.G_CVE}}"

  oci:
    desc: Build {{.G_COMPONENT}} container archive.
    sources:
      - "{{.G_CONTAINER}}"
    generates:
      - "{{.G_OCI}}"
    deps:
      - container
    cmds:
      - podman-remote save --format oci-archive -o "{{.G_OCI}}" {{.G_TAG}}

  rootfs:
    desc: Build {{.G_COMPONENT}} root filesystem archive.
    vars:
      FILES: "{{.G_SOURCE}}/rootfs"
    sources:
      - "{{.FILES}}/**/*"
    generates:
      - "{{.G_ROOTFS}}"
    cmds:
      - mkdir -p "{{.G_TARGET}}/rootfs"
      - tar --exclude '.gitkeep' -czvf "{{.G_ROOTFS}}" -C "{{.FILES}}" "."

  rpm:
    desc: Build {{.G_COMPONENT}} SRPM/RPM package.
    vars:
      SPEC: "{{.G_SOURCE}}/rpm/{{.G_NAME}}-{{.G_COMPONENT}}.spec"
      TOP_DIR: "{{.ROOT_DIR}}/{{.G_TARGET}}/rpm/root"
    sources:
      - "{{.G_ROOTFS}}"
      - "{{.SPEC}}"
    generates:
      - "{{.G_RPM}}"
      - "{{.G_SRPM}}"
    deps:
      - rootfs
    cmds:
      - defer: rm -rf "{{.TOP_DIR}}"
      - rpmbuild
        --define "_rpmdir {{.ROOT_DIR}}/{{.G_TARGET}}/rpm"
        --define "_rpmfilename %{NAME}-%{VERSION}-%{RELEASE}.%{ARCH}.rpm"
        --define "_sourcedir {{.ROOT_DIR}}/{{.G_TARGET}}/rootfs"
        --define "_srcrpmdir {{.ROOT_DIR}}/{{.G_TARGET}}/rpm"
        --define "_topdir {{.TOP_DIR}}"
        -ba
        "{{.SPEC}}"

  sbom:
    desc: Build {{.G_COMPONENT}} SBOM file.
    env:
      SYFT_GOLANG_CAPTURE_SYMBOLS: all
    sources:
      - "{{.G_OCI}}"
    generates:
      - "{{.G_SBOM}}"
    deps:
      - oci
    cmds:
      - syft oci-archive:"{{.G_OCI}}" -o syft-json="{{.G_SBOM}}"

  container:base:
    internal: true
    if: '{{ne .G_COMPONENT "common"}}'
    deps:
      - :common:container
