# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

---
version: "3"

tasks:
  install:
    desc: Build installation ISO image.
    vars:
      CONFIG: src/iso/install/config.toml
      STORAGE: /var/lib/containers/storage

      TARGET: target/iso/install
      ISO: "{{.TARGET}}/{{.G_NAME}}-{{.G_SUFFIX}}-install.iso"
      ROOT: "{{.TARGET}}/root"
    sources:
      - "{{.CONFIG}}"
      - target/installer/container/{{.G_NAME}}-installer-{{.G_SUFFIX}}-iid.txt
      - target/payload/container/{{.G_NAME}}-payload-{{.G_SUFFIX}}-iid.txt
    generates:
      - "{{.ISO}}"
    deps:
      - :container
    cmds:
      - mkdir -p "{{.ROOT}}"
      - defer: rm -rf "{{.ROOT}}"
      - podman-remote run
        --privileged
        --rm
        -v "{{.STORAGE}}:{{.STORAGE}}"
        -v "$WORKSPACE_PATH/{{.CONFIG}}:/config.toml"
        -v "$WORKSPACE_PATH/{{.ROOT}}:/output"
        ghcr.io/osbuild/image-builder:v86.0.0
        build
        --blueprint "/config.toml"
        --bootc-installer-payload-ref
        {{.G_REGISTRY}}/payload:{{.G_SUFFIX}}
        --bootc-ref
        {{.G_REGISTRY}}/installer:{{.G_SUFFIX}}
        --output-dir "/output"
        bootc-installer
      - mv "{{.ROOT}}"/*.iso "{{.ISO}}"

  upgrade:
    desc: Build upgrade ISO image.
    vars:
      PAYLOAD: >-
        target/payload/container/{{.G_NAME}}-payload-{{.G_SUFFIX}}-oci.tar
      SOURCE: src/iso/upgrade

      TARGET: target/iso/upgrade
      ISO: "{{.TARGET}}/{{.G_NAME}}-{{.G_SUFFIX}}-upgrade.iso"
    sources:
      - "{{.PAYLOAD}}"
      - "{{.SOURCE}}/upgrade.sh"
    generates:
      - "{{.ISO}}"
    deps:
      - :payload:oci
    cmds:
      - mkdir -p "{{.TARGET}}"
      - mkisofs -R -J -o "{{.ISO}}" "{{.SOURCE}}" "{{.PAYLOAD}}"
