# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

FROM quay.io/almalinuxorg/almalinux:10.2-20260902
RUN --mount=type=tmpfs,target=/var/cache \
    dnf install -y \
    git-2.52.0 \
    gnupg2-2.4.5 \
    make-4.4.1 \
    podman-remote-5.8.2
RUN useradd -m developer
USER developer
ENV CONTAINER_HOST="unix:///var/run/podman/podman.sock"
