# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

[customizations.installer.kickstart]
contents = """
text --non-interactive
zerombr
clearpart --all --initlabel --disklabel=gpt
reqpart --add-boot
part pv.01 --fstype="lvmpv" --size=1 --grow
volgroup vg0 pv.01
logvol swap --fstype="swap" --vgname=vg0 --name=swap --size=4096
logvol / --fstype="xfs" --vgname=vg0 --name=root --size=10240 --grow
network --bootproto=dhcp --device=link --activate --onboot=on
xconfig --startxonboot
reboot --eject
"""

[customizations.installer.modules]
disable = [
  "org.fedoraproject.Anaconda.Modules.Users"
]
