# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

ARG BASE
ARG CHUNKAH_OUTPUT

FROM ${BASE} AS rootfs
RUN --mount=type=bind,source=target/payload/rpm,target=/tmp/RPMS,ro,z \
    --mount=type=tmpfs,target=/run \
    --mount=type=tmpfs,target=/var/cache \
    --mount=type=tmpfs,target=/var/lib \
    --mount=type=tmpfs,target=/var/log <<'EOF'
dnf install -y \
  @multimedia \
  @sound-and-video \
  @workstation-product-environment \
  /tmp/RPMS/*.rpm
EOF
RUN bootc container lint --fatal-warnings

FROM quay.io/coreos/chunkah:v0.7.0 AS rechunker
ARG CHUNKAH_CHOWN
ARG CHUNKAH_CONFIG_STR
RUN --mount=from=rootfs,target=/chunkah,ro \
    --mount=type=bind,target=/run/src,rw <<'EOF'
chunkah build \
  --label ostree.commit- \
  --label ostree.final-diffid- \
  --max-layers 128 \
  --output oci:/run/src/out \
  --prune /sysroot/

chown -R ${CHUNKAH_CHOWN} /run/src/out
EOF

FROM oci:${CHUNKAH_OUTPUT} AS payload
